const Transaction = require('../models/Transaction');
const Report = require('../models/Report');

async function generateMonthlyReport(year, month, isAuto = true) {
  const prefix = `${year}-${String(month).padStart(2, '0')}`;

  const txs = await Transaction.find({ shiftDate: { $regex: `^${prefix}` } }).lean();

  let totalIn = 0, totalOut = 0;
  const skuMap = {};
  const dailyMap = {};
  const shiftMap = { 1: { in: 0, out: 0 }, 2: { in: 0, out: 0 }, 3: { in: 0, out: 0 } };

  txs.forEach(t => {
    const qty = t.quantity;
    const isIn = t.type === 'IN';

    if (isIn) totalIn += qty; else totalOut += qty;

    if (!skuMap[t.skuName]) skuMap[t.skuName] = { skuName: t.skuName, totalIn: 0, totalOut: 0 };
    if (isIn) skuMap[t.skuName].totalIn += qty; else skuMap[t.skuName].totalOut += qty;

    if (!dailyMap[t.shiftDate]) dailyMap[t.shiftDate] = { in: 0, out: 0 };
    if (isIn) dailyMap[t.shiftDate].in += qty; else dailyMap[t.shiftDate].out += qty;

    if (shiftMap[t.shift]) {
      if (isIn) shiftMap[t.shift].in += qty; else shiftMap[t.shift].out += qty;
    }
  });

  const topModels = Object.values(skuMap)
    .sort((a, b) => (b.totalIn + b.totalOut) - (a.totalIn + a.totalOut))
    .slice(0, 10);

  const report = await Report.findOneAndUpdate(
    { year, month },
    {
      year, month,
      isAutoGenerated: isAuto,
      generatedAt: new Date(),
      summary: {
        totalIn,
        totalOut,
        netBalance: totalIn - totalOut,
        uniqueSkus: Object.keys(skuMap).length,
        topModels,
      },
      dailyData: dailyMap,
      shiftData: shiftMap,
    },
    { upsert: true, new: true }
  );

  return report;
}

module.exports = { generateMonthlyReport };
